### ISSUE TITLE
Inaccurate Treasury referenda track information

### ISSUE THREAD

**Issue by anaelleparity** [polkassembly/polkassembly.github.io#19]
Hello team,

Please note that the max spending amounts for the SmallSpender and BigSpender tracks shown on Polkassembly are **inaccurate,** as shown below:

![Screenshot from 2023-02-26 19-44-07](https://user-images.githubusercontent.com/125848513/221430452-d2077e02-05ca-4701-86fe-c8b6f8628a3c.png)
![Screenshot from 2023-02-26 19-44-49](https://user-images.githubusercontent.com/125848513/221430474-a21f8005-1448-4f3c-9eba-ddfd6c1941c8.png)

In reality, **SmallSpender referenda can request up to 333KSM, while BigSpender referenda can request up to 33,333KSM.** You can find more info here: https://guide.kusama.network/docs/maintain-guides-opengov/#origins-and-tracks
Please update the Polkassembly interface accordingly. 

Thanks! :pray:

**Comment by rajdeep7Singh** [comment]
This was fixed

**Comment by anaelleparity** [comment]
Thank you!
