### ISSUE TITLE
More phishing posts lingering on Polkassembly discussions

### ISSUE THREAD

**Issue by anaelleparity** [polkassembly/polkassembly.github.io#20]
Hello Team,

Just flagging that we are having more and more spam/scam/phishing posts on Polkassembly (Polkadot) lately:
https://polkadot.polkassembly.io/post/235#Iesk1aAldBIdn7gzfFLZ
https://polkadot.polkassembly.io/post/1763
https://polkadot.polkassembly.io/post/1764

Although these are almost immediately reported, the posts are still lingering around after 2 days, instead of being removed.
Can you please advise your Moderation team to take these down ASAP?

Please let the community know if there is anything else that can be done on this matter? As Polkadot OpenGov goes live, it is obvious that these spam posts are going to develop into a massive issue over time if they are not dealt with promptly.

Thanks.

**Comment by niklabh** [comment]
Deleted
